### ISSUE TITLE
IsStackTrace or TryParse

### ISSUE THREAD

**Issue by ThomasArdal** [atifaziz/StackTraceParser#1]
It might be convenient with an IsStackTrace or TryParse method as well. I would love to use StackTraceParser for a project (you know which) but I'm not sure that the input string is a strack trace or not.

I'll write the code if you'd like?

**Comment by atifaziz** [comment]
Would that be as simple as checking if the parser returned any frames?

**Comment by ThomasArdal** [comment]
Ahh. You're absolutely right :+1:
