### ISSUE TITLE
Support stack traces in English locale only

### ISSUE THREAD

**Issue by niemyjski** [atifaziz/StackTraceParser#3]

**Comment by atifaziz** [comment]
@niemyjski What makes you think that? Originally, it was designed (see elmah/Elmah#186) to [work with multiple locales and tested against English, French, Japanese & Arabic](https://github.com/elmah/Elmah/issues/186#issuecomment-134661926). Can you provide details and a stack trace example in a non-English locale that it fails to parse?

**Comment by niemyjski** [comment]
I thought I saw at in the regex, my bad
